addon/components/models-table.js
addon/utils/fmt.js
app/helpers/object-property.js
app/utils/fmt.js
bower.json
config/ember-try.js
package.json
tests/unit/components/models-table-test.js
tests/unit/utils/fmt-test.js

Ready to work without deprecation also in 2.*
To reach this I had to use [`ember-legacy-controllers`](https://github.com/emberjs/ember-legacy-controllers) because `Ember.SortableMixin` doesn't exist anymore in 2.*
I think that the component could be refactored using `Ember.computed.sort()` and `[].sort()` but I didn't have time to look into it.
Also, `ember-legacy-controllers` depends on `ember-legacy-views` at least by now emberjs/ember-legacy-controllers#8

Updated to latest ember-cli with 0 deprecations

---

app/templates/components/models-table.hbs

Current Ember-models-table doesn't behave properly with Forefox du to <div> float positionning. 
This simple patch fix the issue. 
Any chance to get it in a coming version ?

Add div to support Firefox behavior with floating positioning

---

addon/components/models-table.js

Introduced 'sortedByDefault' and 'defaultSortOrder' column properties which are used to initially sort the table. The table will be sorted by the column which has sortedByDefault=true. The sort order is the defaultSortOrder property of that column, or 'asc' by default.

Allow table to be initially sorted

---

addon/components/models-table-server-paginated.js
app/components/models-table-server-paginated.js
app/templates/components/models-table/table-footer.hbs

While models-table works great for certain amounts of data, it cannot work with server-side paginated data. In order to make this possible, I added a second component, `models-table-server-paginated`, which makes this scenario possible.
This component extends the base `models-table` component. For the end user, it can be used (nearly) the same:
```hbs
{{models-table-server-paginated data=model columns=myColumns}}
```
It expects `myData` to be an ember-data query, eg:
```js
model: function() {
return this.store.query('my-model', {});
}
```
It will then take this query and extend it with pagination, sorting and filtering information. All other query parameters added in will remain untouched. Everything else works exactly the same - global filters, column filters etc. still use the same …

Add models-table-server-paginated component

---

addon/components/models-table-server-paginated.js
app/components/models-table-server-paginated.js
app/templates/components/models-table/table-footer.hbs

Currently, if you set your own `pageSize` (e.g. you want the default pageSize to be 50), this will not be displayed in the page size select box correctly. This PR fixes the check for the currently selected page size.

Correctly display initial pageSize setting

---

addon/components/models-table.js
app/templates/components/models-table.hbs
app/templates/components/models-table/global-filter.hbs
tests/dummy/app/templates/index.hbs
tests/integration/components/models-table-test.js

This PR improves various things without changing existing behaviour:
1.) Most observers have been removed, instead `currentPageNumber` is now reset directly in the actions.
2.) `displayDataChangedAction` now receives an object as parameter containing the filter/sorting settings currently in use
3.) A new action `columnsVisibilityChangedAction` has been added, which is called whenever a column is toggled. It receives an array of columns with their current visibility as parameter.
4.) `disableSorting` and `disableFiltering` have been added as options for columns
5.) The behaviour of `sortDirection` and `sortPrecedence` has been slightly improved (`sortDirection` is now completly ignored if no `sortPrecedence` is set), and documented in the dummy app
6.) Allow setting of `filterString` on …

Refactor observers

---

addon/components/models-table.js

If you use a nested propertyName, e.g. `author.name`, an error is thrown when using `Ember.set()`.

Fix issue with nested propertyNames for filters

---

addon/components/models-table.js
app/templates/components/models-table/global-filter.hbs

Something like this could be a nice improvement.
Users can already define the label with `customMessages` and `searchLabel`, and it would be nice to expose the `placeholder` attribute as well.
Feel free to comment about possible additional requirements / if this PR requires any further work.

Add placeholder for search input field

---

addon/components/models-table-server-paginated.js

`lastIndex` of `models-table-server-paginated` was not updated when `arrangedContentLength` is changed.

update lastIndex when arrangedContentLength is changed

---

addon/components/models-table.js

The 3rd argument represents current row. It enables user to create more fine-tuned customization of filterFunction().
Like for example filter by multiple properties at once when columns shows only one value (eg: localized names but only current locale name is visible)

Passing 3rd argument (row) to filterFunction()

---

addon/-private/column.js
addon/components/models-table.js
tests/dummy/app/templates/custom/sort-cell-original-definition.hbs
tests/integration/components/models-table-test.js

With this fix, implementors could have access within the template overrides to the original column object passed into the component.
You could override the _setupColumns function, but this would be 70 extra lines for a one-line change.

Fix #152 - expose original column properties on column model

---

addon/components/models-table-server-paginated.js

When store.query is rejected the state of the component isn't accurate because ```ModelsTableServerPaginated.isLoading``` remains true.  Adding a catch to the data.store's query to set false and add additional ```ModelsTableServerPaginated.isError``` boolean to surface error state in the templates.  
This addition or ```ModelsTableServerPaginated.isError``` is useful when you'd like to indicate to the user that their data might be less than fresh.

Fix table-server-paginated: catch rejected store.query

---

addon/components/models-table-server-paginated.js
tests/integration/components/models-table-server-paginated-test.js

I ran into this issue as well when extending models-table-server-paginated but decided to PR the change proposed by @gossi

Fix #128 - provide default values when filteredContent.meta is empty.

---

addon/templates/components/models-table.hbs

Provides a clean build. Disabled the linter for unused-block-params.

Silence template-lint when building

---

addon/components/models-table-server-paginated.js

This small change makes it possible to easily extend models-table-server-paginated and hook into the `_loadData()` function for custom functionality.

Return promise in _loadData

---

addon/components/models-table-server-paginated.js
addon/templates/components/models-table.hbs
vendor/style.css

This PR replaces the div in model-table's template that has `style='clear:both;'` with a class, making it possible to overwrite this in certain cases. Currently, the div sometimes breaks the layout, and there is no (easy) way to prevent that on a case-by-case basis.
Additionally, the PR fixes a minor bug, where `this.userInteractionObserver()` wasn't called in the paginated table's `sort` action.

Remove inline styles for clearing div & add userInteractionObserver to paginated sort action

---

addon/components/models-table.js
addon/utils/better-compare.js
tests/unit/utils/better-compare-test.js

`Ember.compare()` is really bad at comparing objects/instances like moment.js dates. 
This is especially an problem when using moment-instances as properties. Sorting them doesn't work at all, since they are regular JS-instances and do not implement the Ember.Compareable mixin - `Ember.compare(moment1, moment2)` will simply always return 0, no matter what the dates are.
This PR adds a better-compare method which takes these cases into account, and otherwise falls back to the regular `Ember.compare()` functionality.

Add a better compare function for sorting

---

addon/components/models-table.js

This PR adds a `rebuildTable()` method to the component. This can be used to manually force a complete re-build of the table, resetting all filters/sorting/pagination settings.
This helps to solve  https://github.com/onechiporenko/ember-models-table/issues/131.
A usage example would be to extend the component, and then add something like this:
```js
didReceiveAttrs() {
if (get(this, 'propertyThatIndicatesForceReload')) {
this.rebuildTable();
}
}
```

Add rebuildTable() method to force a complete re-render

---

addon/components/models-table.js

When using a custom filtering option, using `filteringIgnoreCase` can sometimes break.
E.g. I have a custom `filterFunction` that works with an array, it breaks if I don't deactivate `filteringIgnoreCase`. However, I do want to use that functionality for other, regular filters. 
This PR just checks if `filterString` and `cellValue` are strings before applying `toLowerCase()`, else it will just use the existing value.

Check if value/filter is string before applying toLowerCase()

---

addon/components/models-table.js
tests/integration/components/models-table-test.js

Currently, it blows up if an empty array is given as options.

Deactivate filter if predefinedFilterOptions is empty array

---

addon/components/models-table.js
app/templates/components/models-table/columns-dropdown.hbs
tests/dummy/app/controllers/examples/column-sets.js
tests/dummy/app/router.js
tests/dummy/app/templates/examples/column-sets.hbs
tests/dummy/app/templates/index.hbs
tests/helpers/dom.js
tests/integration/components/models-table-test.js

This PR adds the option to specify `columnSets`. These, if specified, will be rendered below the "Show All"...  options in the dropdown.
A column set takes the following configuration:
```js
columnSets: [
{
label: "Name",
showColumns: ['firstName', 'lastName']
}
]
```
By default, if the "Name" button is clicked, it will then show these two columns and hide all other columns (that don't have `mayBeHidden=false`).
You can also modify this behaviour:
```js
{
label: "Name",
showColumns: ['firstName', 'lastName'],
hideOtherColumns: false
}
```
Which will then only show these columns, but leave all other columns as they were before (e.g. visible/hidden).
Then there is also an option to toggle them:
```js
{
label: "Name",
showColumns: ['firstName', 'lastName'],
toggleSet: true
}
```
Which will …

Column sets

---

addon/components/models-table-server-paginated.js

This fixes #219 and now checks for `useFilteringByColumns` in models-table-server-paginated.

Server paginated table should take useFilteringByColumns into account

---

addon/components/models-table-server-paginated.js
addon/components/models-table.js

This commit will allow to set filters explicitly to false. 
Additionally, it allows to overwrite the function which actually mutates the query for easier customization.
In our app, we have a boolean filter that can be true/false. However, currently, it will always strip out the filter if it is set to false, which is not necessarily the same semantic.
The newly added `_setQueryFilter` method can be overwritten to do custom stuff. E.g. you could check for column/filterTitle and do some custom transformations if required.

Improve setting of filters for paginated table

---

app/templates/components/models-table/header-row-filtering.hbs
app/templates/components/models-table/header-row-sorting.hbs
tests/dummy/app/templates/index.hbs
tests/integration/components/models-table-test.js

This PR will extends the feature of custom CSS classes for columns by also assigning this classes to the title and filter of this column.
I want to use these custom class to specify a fixed width for some columns. In the current version I have the following problem: In case the table is empty there aren't any cells that get the custom class, so the width is set to some calculated value. In case a user types into the filter input and gets an empty table for some of the inputs, the table columns therefore change there width dynamically, which I would like to avoid.

add className specified for a column also to header and column filter

---

addon/components/models-table.js
tests/dummy/app/components/delete-row-comp.js
tests/dummy/app/controllers/examples/custom-components-in-cell.js
tests/dummy/app/router.js
tests/dummy/app/routes/examples/custom-components-in-cell.js
tests/dummy/app/templates/components/delete-row-comp.hbs
tests/dummy/app/templates/examples/custom-components-in-cell.hbs
tests/integration/components/models-table-test.js

Same request with componentEdit removed.
This will allow components specified at the column level to be passed in, giving you complete access to the component. This will allow for direct closure actions as well as additional properties to be set on the component.
Additionally the ground work has been laid to implement in-line editing fairly easily.
I did not see where I had the ability to update the documentation
This pull request should solve #270

Allow cell level components to be passed into the component

---

addon/components/models-table.js
tests/dummy/app/templates/examples/display-data-changed-action.hbs
tests/integration/components/models-table-test.js

This will allow the displayDataChangedAction accept a closureAction. SendDisplayDataChangeAction is not required in this mode.
Note: Backward compatibility is preserved. You can still assign a string and set the send variable to true.

Allow displayDataChangedAction to be a closureAction

---

addon/components/models-table.js
addon/components/models-table/cell-content-display.js
addon/components/models-table/cell-content-edit.js
addon/components/models-table/cell.js
addon/components/models-table/row.js
addon/templates/components/models-table/cell-content-display.hbs
addon/templates/components/models-table/cell-content-edit.hbs
addon/templates/components/models-table/cell.hbs
addon/templates/components/models-table/row.hbs
addon/themes/default.js
addon/utils/column.js
app/components/models-table/cell-content-display.js
app/components/models-table/cell-content-edit.js
tests/dummy/app/components/edit-row.js
tests/dummy/app/controllers/examples/in-line-edit.js
tests/dummy/app/router.js
tests/dummy/app/routes/examples/in-line-edit.js
tests/dummy/app/templates/components/edit-row.hbs
tests/dummy/app/templates/examples/in-line-edit.hbs
tests/dummy/mirage/config.js
tests/integration/components/models-table-test.js
tests/integration/components/models-table/cell-content-display-test.js
tests/integration/components/models-table/cell-content-edit-test.js

This is the basis for in-line editing.
The user still has to supply a component that will toggle the edit row state. User must handle save and rollback if a model, or any other logic it not.
Once this is merged, work can proceed on a model-table supplied component for handling the edit/save/cancel buttons and cleanup.

inline edit

---

addon/components/models-table.js

Records were edited outside of the component and I needed the ability to refilter the table. The Public API that is being exposed can/will be expanded upon for other things such as reseting the selected rows.

Added Public API to programmatically interact with the component

---

addon/templates/components/models-table/row.hbs
addon/utils/column.js

Allow any model field to be set as a parameter for routeName
Currently, when a table is defined and a 'routeName' is added, the table will display the propertyName but will link to the 'id' field of the record.
In order to allow for another model property to be set as the parameter for the route, a new routeProperty has been created which defaults to 'id' (enables backward compatibility).
Where a 'routeName' is specified allow another model property to  be used instead of the 'id'
The routeProperty is the parameter to be passed to the route on transition.
E.g
{
'propertyName':'tktNo',
'routeName':'accounts.tickets.ticket',
'routeProperty':'tktNo', // if not set defaults to id
'title':'Ticket No',
},
f0a06ac
Darren Drumm
Darren Drumm
Default New routeProperty to 'id'

Allow any model field to be set as parameter for routeName

---

addon/templates/components/models-table/row.hbs
tests/integration/components/models-table-test.js

Make it easier to customize the `cell` component theme, like extending the classnames for all cell components, that could be applied to simple and route cells.

Use cell component for simple and route cells

---

addon/components/models-table.js
addon/constants/sort-constants.js
package.json
tests/dummy/app/routes/examples/sort-by-filter-by.js
tests/integration/components/models-table-test.js

Adding the ability for sortFunctions to condition on the sort direction. One use case for this type of behavior is wanting undefined (or any particular) values to be shown at the end of the table for ascending and descending sort.
The ideal fix for this is to have sortFunction control the multiplication of the result of the compare function by -1 itself, rather than having this happen where it does now. However, the change proposed here is a backward compatible way of accomplishing the same thing.
Added test for this functionality in models-table-test by doing a sort dependent on direction.
```
1..529
```

Add direction paramater to sortFunction invocation

---

addon/components/models-table/themes/default/summary.ts

The `<a>` tag that calls this action uses the `{{on ...}}` modifier. The default action of following the link is triggered and the app navigates to `#` when this tag is clicked. Since this is an `<a>` tag that is actually playing the role of a button I believe we do not want to perform the default action.

add `preventDefault` to `<a>` tag action

---

addon/components/models-table.ts

I noticed sort performance was very slow for larger sets.  This fixes one of the main reasons.
Previously, `this.pagesCount` was called for every page.  Inside the `pagesCount` property, a calculation is made on `this.arrangedContent.length`.  Retrieving the `arrangedContent` property causes the active sort and filter to be performed.
By taking the page count out of the loop we significantly reduce the number of sorts performed on larger sets (eg, 20+ pages).
This can still be improved - there are still multiple sorts, one every time `arrangedContent` is referenced, but now they are at least not O(N).

Improve sort speed on larger tables of static data.

---

addon/components/models-table.ts

This avoids re-sorting the data many times, and reduces calls to `arrangedContent` for a single table render.
Also replace two uses of `arrangedContent.length` with the alias to improve performance in those locations.
After applying #490, a single table render still re-sorts the data 12 times through various calls to `arrangedContent`.  This change reduces it to just 1 call when changing sort order and 2 when applying a filter.
With both changes applied, rendering, filtering, and sorting tables is fairly fast even with thousands of rows (I measured ~200ms for 10k rows on my system)

Use un-sorted content for arrangedContentLength

---

addon/components/models-table-server-paginated.ts

I got confused by this typo. Was wondering why it is not working as expected until I realized it should be `pagesCount` and not `pageCount`. Let's make sure no one else will be confused by this one. :smile_cat:

fix typo in argument name of API docs

---

addon/components/models-table.hbs
tests/integration/components/models-table-test.js

Since converting to Octane, the ModelsTable component no longer supports attributes being passed in by consumers. This prevents devs from being able to do things like set HTML attributes or use `ember-test-selectors` to test that ModelsTable is being rendered. This change adds splattributes to the `models-table-wrapper` div and adds a test to confirm it's working as expected.

Allow splattributes in ModelsTable component

---

package.json

[Volta](https://volta.sh/) is a JavaScript tool manager that makes it easy to switch between versions of tools like node/yarn/etc between projects. By adding this config, volta users can ensure they are using the expected versions of various tools when working with this project. This has no detrimental effect on non-volta users.
Since the current node range in package.json is backwards compatible to Node 14, I have added the latest Node 14 LTS release in the volta config. When Node 14 is dropped, you can simply update this to the latest Node 16 release, and so on. Additionally, I've pulled in the last yarn 1.x release, so users who have yarn 3 installed don't accidentally overwrite this project's lockfile without the other necessary changes that would be needed to convert to yarn 3.
See …

Add Volta Config

---

addon/components/models-table/themes/default/row-sorting-cell.hbs

In the latest [ember-fontawesome](https://github.com/FortAwesome/ember-fontawesome), fontawesome icons must be drawn with `<svg>` tags, not `<i>` tags.
We can replace `<i>` tags with `<svg>` tags by executing `dom.i2svg()`.
https://github.com/FortAwesome/ember-fontawesome/blob/master/UPGRADING.md#mixed-modes-with-automatic-replacement-of-i-tags-to-svg
However, if the `if` conditional branch is in an `<i>` tag, it is not possible to switch between asc and desc when replacing with `dom.i2svg()`

Enable sortIcon to be used with ember-fontawesome@v5

---

package.json

Much like ember-cli-page-object, this is exposed via test-support, so webpack has issues compiling unless it's a dep
See also #542

Move ember-power-select to dep
